language: node_js
before_script:
  - git submodule update --init
  # - npm install -g codeclimate-test-reporter
node_js:
  - 10
  - 12
  - 14
script:
  - npm run ci-test
# after_script:
#   - codeclimate-test-reporter < coverage/lcov.info
#   - coveralls < coverage/lcov.info
